name: Assign and Label PR

on:
  pull_request:
    types:
      - opened

jobs:
  assign_and_label_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign PR to author and add label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${{ github.actor }}" --add-label "Pendiente"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
