name: PR Workflow

on:
  pull_request:
    types: [opened, review_requested, review_request_removed, review_submitted]

jobs:
  manage_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign PR to author and add initial label
        if: github.event.action == 'opened'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${{ github.actor }}" --add-label "Pendiente"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add reviewer to PR
        if: github.event.action == 'opened'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "jrodrigues-webimpacto"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Change label to Revisar
        if: github.event.action == 'review_requested'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --remove-label "Pendiente" --add-label "Revisar"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Change label to Listo
        if: github.event.action == 'review_submitted' && github.event.review.state == 'approved'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --remove-label "Revisar" --add-label "Listo"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
